---

- name: Add Vagrant key
  become: true
  apt_key: url=https://apt.releases.hashicorp.com/gpg

- name: Add Vagrant repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: vagrant

- name: Install Vagrant
  become: true
  apt:
    name: vagrant
    state: present
