---

- name: Add Vagrant key
  become: true
  apt_key: url=https://apt.releases.hashicorp.com/gpg

- name: Add Vagrant repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: vagrant

- name: Install Vagrant
  become: true
  apt:
    name: vagrant
    state: present

- name: Dependencies for vagrant-libvirt
  become: true
  apt:
    name:
      - vagrant
      - ruby-libvirt
    state: build-dep

- name: Dependencies for vagrant-libvirt
  become: true
  apt:
    name:
      - qemu
      - libvirt-daemon-system
      - libvirt-clients
      - ebtables
      - dnsmasq-base
      - libxslt-dev
      - libxml2-dev
      - libvirt-dev
      - zlib1g-dev
      - ruby-dev
      - libguestfs-tools
    state: present

- name: Install vagrant-libvirt plugin
  shell: vagrant plugin install vagrant-libvirt

- name: Install vagrant-vbguest plugin
  shell: vagrant plugin install vagrant-vbguest

- name: Install vagrant-hostupdater plugin
  shell: vagrant plugin install vagrant-hostsupdater
